# Generated by Django 5.1.3 on 2024-11-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECBApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='totalConsumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
