# Generated by Django 5.1.3 on 2024-11-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECBApp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
