# Generated by Django 5.1.3 on 2024-11-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECBApp', '0004_alter_bill_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
