# Generated by Django 5.1.3 on 2024-11-16 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECBApp', '0005_alter_bill_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='dueDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
