# Generated by Django 5.1.4 on 2024-12-10 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECBApp', '0009_payment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='billDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='dueDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='readingDateFrom',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='readingDateTo',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='tariffRatePerKwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='totalConsumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
